name: release
run-name: release
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    tags:
      - v*
jobs:
  buildAndSign:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: install go deps
        run: |
          go mod tidy
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: go build
        env:
          CC: x86_64-w64-mingw32-gcc
        run: |
          export BUILD_USER='${{github.actor}}'
          make build
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3.1.0
        with:
          install-only: true
      - name: upx
        run: |
          make upx
      - name: uploadArtifact
        id: uploadArtifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: hh-lol-prophet
          path: bin/hh-lol-prophet.exe
      - name: removeUnsignedBin
        run: |
          rm bin/hh-lol-prophet.exe
      - name: sign
        uses: SignPath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORG_ID }}'
          project-slug: 'hh-lol-prophet'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{steps.uploadArtifact.outputs.artifact-id}}'
          wait-for-completion: true
          output-artifact-directory: 'bin'
          parameters: |
            Version: "${{ github.ref_name }}"
      - name: uploadSignArtifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: hh-lol-prophet-bin
          path: bin/
  releaseApp:
    needs: buildAndSign
    runs-on: arc-runner-set
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [ '1.23' ]
    env:
      GOPROXY: https://goproxy.buffge.com,direct
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: mkdir bin
        run: |
          mkdir bin
      - name: downloadSign
        uses: actions/download-artifact@v4.1.8
        with:
          name: hh-lol-prophet-bin
          path: ./bin
      - name: package
        run: |
          mv bin hh-lol-prophet-${{ github.ref_name }}
          zip -r hh-lol-prophet-${{ github.ref_name }}.zip ./hh-lol-prophet-${{ github.ref_name }}
          mkdir release-package
          mv hh-lol-prophet-${{ github.ref_name }}.zip release-package
          mv hh-lol-prophet-${{ github.ref_name }}/hh-lol-prophet.exe release-package
      - name: upload release
        run: |
          s3cmd sync release-package/ s3://buff-pub/hh-lol-prophet/${{ github.ref_name }}/
      - name: generate tag message env
        run: |
          echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${{ github.ref_name }})" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "${{ github.env.TAG_MESSAGE }}"
          files: |
            release-package/hh-lol-prophet-${{ github.ref_name }}.zip
      - uses: buffge/dingtalk-action@34743c736212579f8ff99d2dca75879b56371796
        if: ${{ success() }}
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        with:
          msgtype: markdown
          title: " hh-lol-propher 成功"
          text: |
            **<font color=#54aeff size=4>az-blog 构建成功</font>**

            **<font size=4>commitMsg: ${{ github.event.head_commit.message }}</font>**
      - uses: buffge/dingtalk-action@34743c736212579f8ff99d2dca75879b56371796
        if: ${{ failure() }}
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        with:
          msgtype: markdown
          title: "hh-lol-propher 失败"
          text: |
            **<font color=#cf222e size=4>az-blog 构建失败</font>**

            **<font size=4>commitMsg: ${{ github.event.head_commit.message }}</font>**